// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://limzwmzlwltufydsnfmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbXp3bXpsd2x0dWZ5ZHNuZm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDk5NjYsImV4cCI6MjA2MzY4NTk2Nn0.Ok_3Uzf90C_l00vURa32XACBuvQmapTYFMQ2IDJ7ZCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);